name: CI
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Escolha o ambiente: dev, staging ou qa"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - staging
        - qa
      testSuite:
        description: "Escolha a suíte de teste: Login, Product ou Users"
        required: true
        default: "all"
        type: choice
        options:
        - all
        - login
        - product
        - users
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4

        - name: Install Dependencies
          run: npm install

        - name: Install Allure Command-line Tool
          run: npm install -g allure-commandline

        - name: 🧪 Test
          run: npm run test:${{ github.event.inputs.testSuite }}
          env:
            ENV: ${{ github.event.inputs.environment }}

        - name: Generate Allure Report
          run: npm run allure:report
          
        - name: Upload reports
          uses: actions/upload-artifact@v4
          if: always()
          with:
            name: reports - ${{ github.event.inputs.testSuite }} - ${{ github.event.inputs.environment }}
            path: test/reports/generateReport/